linters:
  BorderZero:
    enabled: false

  Indentation:
    enabled: true
    width: 2

  ColorKeyword:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  PlaceholderInExtend:
    enabled: false
