name: Zanata
sub-name: Open Translation, for Everyone
desription: Zanata is a web-based system for translators, content creators and developers to manage localisation projects.

paginate: 10

markdown: rdiscount
pygments: true
safe: true
lsi: false

source: ./src
destination: ./_site

include: [.htaccess]
exclude: [zanata-proto.sublime-project, zanata-proto.sublime-workspace, config.rb, sass]

